unbind-key C-z
set-option -g prefix C-z

set-option -g default-command $SHELL

# Set XTerm key bindings
setw -g xterm-keys on

# Set current path to new panes
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set reload key to r
bind r source-file ~/.tmux.conf

# Use vim bindings
setw -g mode-keys vi

set -g clock-mode-colour green

# Set status bar
set-window-option -g status-left "#(~/.tmux/updates.py)"
set-window-option -g status-left-fg white
set-window-option -g status-left-bg black
set-window-option -g status-right "#(~/.tmux/ssid.sh) #(~/.tmux/headset.py)#[bg=black]#[fg=white] %H:%M #(~/.tmux/battery-bg.sh)"
set-window-option -g status-right-fg black
set-window-option -g status-right-bg green
set-option -g status-bg green
set-window-option -g window-status-format "  #I: #W  "
set-window-option -g window-status-bg green
set-window-option -g window-status-fg black
set-window-option -g window-status-current-format "  #I: #W  "
set-window-option -g window-status-current-bg black
set-window-option -g window-status-current-fg green

#set -g lock-command "cmatrix -b"
#set -g lock-after-time 90
#set -g lock-server on
